### PR TITLE
fix: `any` not a keyword

### LINKED ISSUE #436: `any` is not a keyword
But it should be!

### PR DESCRIPTION
**Pull request by TG1999**
Signed-off-by: tushar goel <tushar.goel.dav@gmail.com>

This patch closes #436  and includes:
- [ ] A relevant test
- [ ] A relevant documentation update

### CODE REVIEW

File: lib/tokeniser.js [hunk 1]
```diff
@@ -72,7 +72,8 @@ const nonRegexTerminals = [
   "short",
   "true",
   "unsigned",
-  "void"
+  "void",
+  "any"
```
Comment (saschanaz) [inline lib/tokeniser.js]: I would keep this in alphabet order, so probably line 56.

**Comment by TG1999** [comment]
Hi @saschanaz I have wrote one test case for any and one for int32 I am opening another issue for writing test cases for solving #251 . Please merge this one

File: lib/tokeniser.js [hunk 2]
```diff
@@ -53,6 +69,7 @@ const nonRegexTerminals = [
   "Infinity",
   "NaN",
   "Promise",
+  "any",
   "async",
```
Comment (saschanaz) [inline lib/tokeniser.js]: Again while you are at it, could you remove `async` and `constructor` from this list? They are already in `argumentNameKeywords` so they are redundant.

File: lib/tokeniser.js [hunk 3]
```diff
@@ -15,6 +15,22 @@ const tokenRe = {
   "other": /[^\t\n\r 0-9A-Za-z]/y
 };
 
+export const typeNameKeywords=[
```
Comment (saschanaz) [inline lib/tokeniser.js]:
```suggestion
export const typeNameKeywords = [
```

Make sure the code format be consistent with other lines 😁

File: lib/productions/type.js [hunk 4]
```diff
@@ -62,7 +62,7 @@ function type_suffix(tokeniser, obj) {
 function single_type(tokeniser, typeName) {
   let ret = generic_type(tokeniser, typeName) || primitive_type(tokeniser);
   if (!ret) {
-    const base = tokeniser.consume("identifier", ...stringTypes);
+    const base = tokeniser.consume("identifier", "any", ...stringTypes, ...typeNameKeywords);
```
Comment (saschanaz) [inline lib/productions/type.js]: This is okay, but we could probably move `any` into `typeNameKeywords` 👍

File: test/invalid/baseline/Int32-keyword.txt [hunk 5]
```diff
@@ -0,0 +1,3 @@
+Syntax error at line 1 in Int32-keyword.webidl:
```
Comment (saschanaz) [inline test/invalid/baseline/Int32-keyword.txt]: 👍 but could you rename this as `int32array-keyword` because

* I would keep filenames in lowercase, just for consistency
* We may get `int32` in the future, so better be more specific

Sorry to be picky here 😱

**Comment by TG1999** [comment]
@saschanaz all changes made :grinning:

**Comment by saschanaz** [comment]
If you want to continue your great works, #256 seems to be next easiest issue to fix.

It might be more complex than previous issues, we want to modify parser logic to allow a set of string in extended attributes. (In `lib/productions/extended-attribute.js`)

Probably we'll want to copy `identifiers()` function there and make it parse strings.

I can provide more details but it's already time to bed, so if you need more information, you might try reading existing code before I return.

**Comment by TG1999** [comment]
Hi @saschanaz I will surely like to work on this

**Comment by TG1999** [comment]
I have read the existing code from their I understood ```export function identifiers(tokeniser) {
  const ids = list(tokeniser, { parser: Token.parser(tokeniser, "identifier"), listName: "identifier list" });
  if (!ids.length) {
    tokeniser.error("Expected identifiers but none found");
  }
  return ids;
}``` I have to implement this functionality In lib/productions/extended-attribute.js so from where I will get the string that I have to parse

**Comment by saschanaz** [comment]
I would modify `identifiers` into `tokens` and add a new function `identifiersOrStrings`, all in `extended-attribute.js`:

```js
function tokens(tokeniser, tokenName) {
  const toks = list(tokeniser, {
    parser: Token.parser(tokeniser, tokenName),
    listName: tokenName + " list"
  });
  if (!toks.length) {
    tokeniser.error(`Expected ${tokenName}s but none found`);
  }
  return toks;
}

function identifiersOrStrings(tokeniser) {
  return tokens(tokeniser, "identifier") || tokens(tokeniser, "string");
}
```

And replace existing `identifiers(tokeniser)` into `identifiersOrStrings(tokeniser)`. This will allow `("str1", "str2")` where we want.

**Comment by TG1999** [comment]
Okay I got it @saschanaz , will be making a PR soon then we can discuss more changes on the PR itself.

**Comment by saschanaz** [comment]
Looking forward to the PR! (If you are blocked on anything, I'm always here to help 👍)

**Comment by TG1999** [comment]
Hi, right now I am stucked with some college work, gill try to get back to you by weekend and thanks for your help 😄
