### PR TITLE
fix: consume return type for promise subtype

### LINKED ISSUE #168: Error parsing generic type with Promise<void>
Parsing https://github.com/w3c/web-platform-tests/blob/master/interfaces/BackgroundSync.idl is broken by https://github.com/w3c/webidl2.js/commit/621d0b6c17c6f34cf6b0b5c0976abb069703d4eb. 

```
Got an error during or right after parsing `interface SyncManager`: Error parsing generic type Promise, line 11 (tokens: "void> register(DOMString")
[
    {
        "type": "void",
        "value": "void",
        "trivia": ""
    },
    {
        "type": "other",
        "value": ">",
        "trivia": ""
    },
    {
        "type": "identifier",
        "value": "register",
        "trivia": " "
    },
    {
        "type": "other",
        "value": "(",
        "trivia": ""
    },
    {
        "type": "identifier",
        "value": "DOMString",
        "trivia": ""
    }
]
```

It looks like the relevant IDL is:

```
[Exposed=(Window,Worker)]
interface SyncManager {
  Promise<void> register(DOMString tag);
  Promise<sequence<DOMString>> getTags();
};
```

### PR DESCRIPTION
**Pull request by saschanaz**
This PR:

1. fixes #168 
2. fixes a bug where `Promise<void>?` was allowed (See https://heycam.github.io/webidl/#prod-NonAnyType)
1. adds generic/string type terminals as keywords
2. splits generic type parser into a new function `generic()`.
3. `return_type()` now does not throw, instead the callers should manage errors  with proper messages

### CODE REVIEW

File: lib/webidl2.js [hunk 1]
```diff
@@ -302,41 +312,55 @@
...
+          break;
+        case "sequence":
+        case "FrozenArray":
+          ret.idlType = type_with_extended_attributes(typeName);
+          break;
+        case "record":
+          if (probe("[")) error("Record key cannot have extended attribute");
+          ret.idlType = [];
+          const keyType = consume(...stringTypes);
+          if (!keyType) error("Record key must be DOMString, USVString, or ByteString");
```
Comment (marcoscaceres) [inline lib/webidl2.js]: nit: 
```
`Record key must be one of: ${stringTypes.join(", ")}.`
```

Then we don't need to maintain it if a new type gets added.

File: lib/webidl2.js [hunk 2]
```diff
@@ -302,41 +312,55 @@
...
+          ret.idlType.push(Object.assign({ type: typeName }, EMPTY_IDLTYPE, { idlType: keyType.value }));
+          consume(",") || error("No comma after record key type");
```
Comment (marcoscaceres) [inline lib/webidl2.js]: s/`error("No`/`error("Missing`

File: lib/webidl2.js [hunk 3]
```diff
@@ -302,41 +312,55 @@
...
+          const valueType = type_with_extended_attributes(typeName) || error("Error parsing generic type record");
+          ret.idlType.push(valueType);
+          break;
+      }
+      if (!ret.idlType) error(`Error parsing generic type ${name.type}`);
+      consume(">") || error(`No closing bracket after ${name.type}`);
```
Comment (marcoscaceres) [inline lib/webidl2.js]: As above: No -> Missing

File: lib/webidl2.js [hunk 4]
```diff
@@ -545,7 +569,7 @@
       const name = consume(ID) || error("No name for callback");
       ret = current = { type: "callback", name: sanitize_name(name.value, "callback") };
       consume("=") || error("No assignment in callback");
-      ret.idlType = return_type();
+      ret.idlType = return_type() || error("No return type");
```
Comment (marcoscaceres) [inline lib/webidl2.js]: As above.

File: lib/webidl2.js [hunk 5]
```diff
@@ -611,7 +635,7 @@
         else if (consume("deleter")) ret.deleter = true;
         else break;
       }
-      ret.idlType = return_type();
+      ret.idlType = return_type() || error("No return type");
```
Comment (marcoscaceres) [inline lib/webidl2.js]: As above

**Comment by saschanaz** [comment]
I didn't really like double colons in `Got an error during or right after parsing `interface Foo`: Record key must be one of: ByteString, DOMString, USVString` so I replaced the second one with `->`. Not sure it's best, though.

**Comment by marcoscaceres** [comment]
How about instead of "must be one of ->".., "must be one of `ByteString`, `DOMString`, `USVString`"

**Comment by marcoscaceres** [comment]
updated comment above

**Comment by saschanaz** [comment]
How about just `Record key must be a string type`?

**Comment by saschanaz** [comment]
v13.0.0 because of #175.
