### PR TITLE
fix parse() throws error on valid ReflectOnly Blink extended attributes

### LINKED ISSUE #256: parse() throws error on valid ReflectOnly Blink extended attributes
According to the Blink IDL Extended Attributes spec, [ReflectOnly has two valid forms](https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/bindings/IDLExtendedAttributes.md#ReflectOnly_a):

    [Reflect, ReflectOnly="on"] attribute DOMString toggle;
    // Parens may contain 2 to n values.
    [Reflect=q, ReflectOnly=("anonymous", "use-credentials")] attribute DOMString quarter;

The second format is causing error such as the following to be thrown:

    Got an error during or right after parsing `interface HTMLImageElement`: Expected
    identifiers but none found, line 33 (tokens: "\"anonymous\",\"use-credentials\"),")

There are 11 files in Chromium (listed below) that trigger this error. I've [already verified](https://bugs.chromium.org/p/chromium/issues/detail?id=920009) that the Blink IDL spec is correct.

blink/renderer/core/html/html_element.idl
blink/renderer/core/html/html_link_element.idl
blink/renderer/core/html/html_table_cell_element.idl
blink/renderer/core/html/html_anchor_element.idl
blink/renderer/core/html/forms/html_form_element.idl
blink/renderer/core/html/html_area_element.idl
blink/renderer/core/html/html_script_element.idl
blink/renderer/core/html/html_iframe_element.idl
blink/renderer/core/html/html_image_element.idl
blink/renderer/core/html/media/html_media_element.idl
blink/renderer/core/dom/element.idl

I would appreciate some haste in addressing this. This affects tooling I've built to increase my velocity at [documenting new web platform APIs](https://developer.mozilla.org/en-US/profiles/jpmedley). If I can assist in some further way, will be happy to do so.

Thanks

### PR DESCRIPTION
**Pull request by TG1999**
Signed-off-by: tushar goel <tushar.goel.dav@gmail.com>

This patch closes #256  and includes:
- [x] A relevant test
- [ ] A relevant documentation update

### CODE REVIEW

**Comment by TG1999** [comment]
@saschanaz looks good to merge ?

**Comment by saschanaz** [comment]
Yes, given that we have a baseline test 👍

-Kagami

________________________________

**Comment by TG1999** [comment]
@saschanaz can you guide me a little how can I start proceed to write a baseline test for this ?

**Comment by saschanaz** [comment]
Sure! For now just copy-pasting the code in the OP of #256 should be sufficient.

-Kagami

________________________________

**Comment by TG1999** [comment]
Can you highlight the required comment for me, so we can close this issue ASAP and start working on another issue.

**Comment by saschanaz** [comment]
Sorry, I should have provided more detail. The code would be:

```webidl
interface mixin Reflector {
  [Reflect, ReflectOnly="on"] attribute DOMString toggle;
  // Parens may contain 2 to n values.
  [Reflect=q, ReflectOnly=("anonymous", "use-credentials")] attribute DOMString quarter;
};
```

Recall what you did in #435 👍

**Comment by TG1999** [comment]
@saschanaz Done with the tests.

File: lib/productions/extended-attributes.js [hunk 1]
```diff
@@ -1,8 +1,30 @@
...
+ * @param {import("../tokeniser").Tokeniser} tokeniser
+ * @param {string} tokenName
+ */
+function tokens(tokeniser, tokenName) {
+  const toks = list(tokeniser, {
+    parser: Token.parser(tokeniser, tokenName),
+    listName: tokenName + " list"
+  });
+  if (!toks.length) {
+    tokeniser.error(`Expected ${tokenName}s but none found`);
```
Comment (saschanaz) [inline lib/productions/extended-attributes.js]: Could you move this length check to `identifiersOrStrings()? Otherwise it won't consume strings as it fails consuming identifiers first.

Comment (TG1999) [reply lib/productions/extended-attributes.js]: Since we are getting toks after parsing them, so should I also parse it first?

Comment (saschanaz) [reply lib/productions/extended-attributes.js]: Exactly.

**Comment by TG1999** [comment]
@saschanaz I am moving it to syntax then I am getting this error while npm run acquire
/webidl2.js/test/util/collect.js:35
        throw error;
        ^

WebIDLParseError: Syntax error at line 4 in reflector-interface.webidl, since `interface mixin Reflector`:
q, ReflectOnly=("anonymous", "use-credentials")]
                ^ Expected identifiers but none found

**Comment by saschanaz** [comment]
Maybe you have to `npm run build && npm run acquire`?

File: lib/productions/extended-attributes.js (hunk 1 above)
Comment (TG1999) [reply lib/productions/extended-attributes.js]: Then I think token functions is of no use

**Comment by TG1999** [comment]
> Maybe you have to `npm run build && npm run acquire`?

@saschanaz still getting same error

**Comment by saschanaz** [comment]
Oh, I incorrectly assumed `tokens()` would return a falsy value. `||` won't work, instead we should probably do something like:

```jjs
function identifiersOrStrings(tokeniser) {
  let toks = tokens(tokeniser, "identifier");
  if (toks.length) {
    return toks;
  }
  toks = tokens(tokeniser, "string");
  if (toks.length) {
    return toks;
  }
  tokeniser.error(`Expected identifiers or strings but none found`);
}
```

**Comment by TG1999** [comment]
@saschanaz I think we should have it in invalid not in syntax. what say ?

**Comment by saschanaz** [comment]
The new error messages suggest all is well, you can put it in `syntax` and you won't see any failure this time.

**Comment by TG1999** [comment]
@saschanaz please have a look

**Comment by saschanaz** [comment]
Hmm, please commit `npm run build && npm run acquire` (without `dist/`) and those will be fixed.

File: lib/productions/extended-attributes.js [hunk 2]
```diff
@@ -1,8 +1,35 @@
...
+function tokens(tokeniser, tokenName) {
+  const toks = list(tokeniser, {
+    parser: Token.parser(tokeniser, tokenName),
+    listName: tokenName + " list"
+  });
+  return toks;
+}
+
+// This will allow a set of strings to be parsed
+ function identifiersOrStrings(tokeniser) {
```
Comment (saschanaz) [inline lib/productions/extended-attributes.js]:
```suggestion
function identifiersOrStrings(tokeniser) {
```

One nit 😁

File: lib/productions/extended-attributes.js [hunk 3]
```diff
@@ -1,8 +1,35 @@
...
+ */
+function tokens(tokeniser, tokenName) {
+  const toks = list(tokeniser, {
+    parser: Token.parser(tokeniser, tokenName),
+    listName: tokenName + " list"
+  });
+  return toks;
+}
+
+// This will allow a set of strings to be parsed
```
Comment (saschanaz) [inline lib/productions/extended-attributes.js]:
```suggestion
/**
 * This will allow a set of identifiers and strings to be parsed.
 */
```

This way IDEs can provide a description when a dev hovers on a relevant function call.

**Comment by TG1999** [comment]
> Hmm, please commit `npm run build && npm run acquire` (without `dist/`) and those will be fixed.

Doing that is giving me error which I have talked about earlier.

**Comment by saschanaz** [comment]
> Doing that is giving me error which I have talked about earlier.

I tried it myself and it went as expected, did you retried after your last commit?

**Comment by TG1999** [comment]
Yes

**Comment by saschanaz** [comment]
Okay, given that you already wrote good codes, let me commit the result...

**Comment by TG1999** [comment]
@saschanaz looks good to merge now ?

File: lib/productions/extended-attributes.js [hunk 4]
```diff
@@ -1,8 +1,37 @@
...
+function tokens(tokeniser, tokenName) {
+  const toks = list(tokeniser, {
+    parser: Token.parser(tokeniser, tokenName),
+    listName: tokenName + " list"
+  });
+  return toks;
+}
+
+/**
+ * This will allow a set of identifiers or strings to be parsed.
```
Comment (saschanaz) [inline lib/productions/extended-attributes.js]: Last nit:

```suggestion
 * This will allow a set of identifiers or strings to be parsed.
 * @param {import("../tokeniser").Tokeniser} tokeniser
```

**Comment by TG1999** [comment]
No problem @saschanaz and thanks for guiding me 😊
